{ config, lib, pkgs, ... }:

let
  cfg = config.services.zhihu-cookie-refresh;

  playwright-browsers = pkgs.playwright-driver.passthru.browsers-chromium;
  chromiumRevision = pkgs.playwright-driver.passthru.browsersJSON.chromium.revision;
  chromiumPath = "${playwright-browsers}/chromium-${chromiumRevision}/chrome-linux64/chrome";

  refreshScript = pkgs.writeText "zhihu-cookie-refresh.js" ''
    const { chromium } = require('${pkgs.playwright-driver}');
    const { readFileSync, writeFileSync } = require('fs');

    const fallbackSeedCookies = ${builtins.toJSON cfg.seedCookies};
    const envFile = process.env.ENV_FILE;

    // Try to read cookies from previous refresh; fall back to hardcoded seed
    function getSeedCookies() {
      try {
        const content = readFileSync(envFile, 'utf8');
        const match = content.match(/ZHIHU_COOKIES='(.+)'/);
        if (match && match[1].includes('z_c0=')) {
          console.log('Using cookies from previous refresh');
          return match[1].replace(/'\\'''/g, "'");
        }
      } catch {}
      console.log('Using fallback seed cookies');
      return fallbackSeedCookies;
    }

    (async () => {
      const seedCookies = getSeedCookies();

      if (!seedCookies || !seedCookies.includes('z_c0=')) {
        console.log('No valid seed cookies (missing z_c0). Skipping refresh.');
        process.exit(0);
      }

      const browser = await chromium.launch({
        headless: true,
        executablePath: process.env.CHROMIUM_EXEC_PATH,
        args: ['--no-sandbox', '--disable-setuid-sandbox',
               '--disable-blink-features=AutomationControlled',
               '--disable-dev-shm-usage',
               '--proxy-server=direct://',
               '--disable-features=IsolateOrigins,site-per-process'],
      });

      try {
        const context = await browser.newContext({
          userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
          viewport: { width: 1920, height: 1080 },
          locale: 'zh-CN',
        });

        // Seed cookies into browser context
        const cookiePairs = seedCookies.split(';').map(s => s.trim()).filter(Boolean);
        const cookieObjects = cookiePairs.map(pair => {
          const idx = pair.indexOf('=');
          return {
            name: pair.substring(0, idx),
            value: pair.substring(idx + 1),
            domain: '.zhihu.com',
            path: '/',
          };
        });
        await context.addCookies(cookieObjects);

        // Hide webdriver flag before any page loads
        await context.addInitScript(() => {
          Object.defineProperty(navigator, 'webdriver', { get: () => undefined });
        });

        const page = await context.newPage();
        await page.goto('https://www.zhihu.com/explore', {
          waitUntil: 'domcontentloaded', timeout: 30000,
        });
        console.log('Page URL:', page.url());

        if (page.url().includes('unhuman')) {
          console.error('Anti-bot verification triggered');
          process.exit(2);
        }

        // Simulate user activity to trigger JS cookie generation
        await page.waitForTimeout(3000);
        await page.mouse.move(400, 300);
        await page.evaluate(() => window.scrollBy(0, 300));
        await page.waitForTimeout(2000);

        // Wait for __zse_ck cookie (generated by JS)
        let zseCk = null;
        for (let i = 0; i < 20; i++) {
          const cookies = await context.cookies('https://www.zhihu.com');
          if (i === 0) console.log('Browser cookies:', cookies.map(c => c.name).join(', '));
          const ck = cookies.find(c => c.name === '__zse_ck');
          if (ck && ck.value) { zseCk = ck.value; break; }
          await page.evaluate(() => window.scrollBy(0, 100));
          await page.waitForTimeout(2000);
        }
        if (!zseCk) { console.error('Failed to get __zse_ck'); process.exit(1); }
        console.log('Got __zse_ck:', zseCk.substring(0, 10) + '...');

        // Merge: start with seed cookies, then overlay browser cookies
        // This preserves any seed cookie fields the browser didn't generate
        const seedMap = new Map();
        cookiePairs.forEach(pair => {
          const idx = pair.indexOf('=');
          if (idx > 0) seedMap.set(pair.substring(0, idx), pair.substring(idx + 1));
        });

        const browserCookies = await context.cookies('https://www.zhihu.com');
        browserCookies.forEach(c => seedMap.set(c.name, c.value));

        if (!seedMap.has('z_c0')) {
          console.error('Merged cookies lost z_c0. Not overwriting env file.');
          process.exit(1);
        }

        const cookieStr = Array.from(seedMap.entries()).map(([k, v]) => k + '=' + v).join('; ');
        console.log('Merged', seedMap.size, 'cookies (seed:', cookiePairs.length, '+ browser:', browserCookies.length, ')');

        // Write env file in shell-sourceable format
        writeFileSync(envFile,
          "ZHIHU_COOKIES='" + cookieStr.replace(/'/g, "'\\'''") + "'\n",
          { mode: 0o600 });

        console.log('Wrote', seedMap.size, 'cookies to env file');
      } finally {
        await browser.close();
      }
    })().catch(e => {
      console.error(e);
      process.exit(1);
    });
  '';
in
{
  options.services.zhihu-cookie-refresh = {
    enable = lib.mkEnableOption "Zhihu cookie refresh via headless Chromium";

    seedCookies = lib.mkOption {
      type = lib.types.str;
      default = "";
      description = ''
        Fallback seed cookies (semicolon-separated) for the first run only.
        Must include at least `z_c0` for authenticated access.
        After the first successful refresh, subsequent runs read cookies
        from the env file automatically.
      '';
    };

    envFile = lib.mkOption {
      type = lib.types.str;
      default = "/var/lib/rsshub/zhihu-cookies.env";
      description = "Path to write the ZHIHU_COOKIES env file (shell-sourceable).";
    };

    user = lib.mkOption {
      type = lib.types.str;
      default = "rsshub";
      description = "User to run the refresh service as.";
    };

    group = lib.mkOption {
      type = lib.types.str;
      default = "rsshub";
      description = "Group to run the refresh service as.";
    };

    interval = lib.mkOption {
      type = lib.types.str;
      default = "4h";
      description = "How often to refresh cookies (systemd time span).";
    };

    onCalendar = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = "Optional OnCalendar schedule (overrides interval if set).";
    };

    initialDelay = lib.mkOption {
      type = lib.types.str;
      default = "2min";
      description = "Delay after boot before first refresh.";
    };

    restartService = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = "rsshub.service";
      description = "Service to restart after cookie refresh. Set to null to disable.";
    };
  };

  config = lib.mkIf cfg.enable {
    systemd.tmpfiles.rules = [
      "f ${cfg.envFile} 0600 ${cfg.user} ${cfg.group} -"
    ];

    systemd.services.zhihu-cookie-refresh = {
      description = "Refresh Zhihu cookies via headless Chromium";
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];
      path = [ pkgs.nodejs_22 ];
      environment = {
        PLAYWRIGHT_BROWSERS_PATH = "${playwright-browsers}";
        CHROMIUM_EXEC_PATH = chromiumPath;
        ENV_FILE = cfg.envFile;
      };
      serviceConfig = {
        Type = "oneshot";
        User = cfg.user;
        Group = cfg.group;
        ExecStart = "${pkgs.nodejs_22}/bin/node ${refreshScript}";
        TimeoutStartSec = "180";
      } // lib.optionalAttrs (cfg.restartService != null) {
        ExecStartPost = "+${pkgs.systemd}/bin/systemctl restart ${cfg.restartService}";
      };
    };

    systemd.timers.zhihu-cookie-refresh = {
      wantedBy = [ "timers.target" ];
      timerConfig = {
        OnBootSec = cfg.initialDelay;
        Persistent = true;
        RandomizedDelaySec = "5min";
      } // (if cfg.onCalendar != null then {
        OnCalendar = cfg.onCalendar;
      } else {
        OnUnitActiveSec = cfg.interval;
      });
    };
  };
}
